/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Check API health */
    get: operations["get_health_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Login */
    post: operations["login_api_v1_auth_login_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/refresh": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Refresh */
    post: operations["refresh_api_v1_auth_refresh_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Logout */
    post: operations["logout_api_v1_auth_logout_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Me */
    get: operations["me_api_v1_auth_me_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/analytics/overview": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Overview */
    get: operations["get_overview_api_v1_analytics_overview_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/analytics/customers-by-product": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Customers By Product */
    get: operations["get_customers_by_product_api_v1_analytics_customers_by_product_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/analytics/interactions-trend": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Interactions Trend */
    get: operations["get_interactions_trend_api_v1_analytics_interactions_trend_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/analytics/follow-ups": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Analytics Follow Ups */
    get: operations["get_analytics_follow_ups_api_v1_analytics_follow_ups_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/users": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Users */
    get: operations["list_users_api_v1_users_get"];
    put?: never;
    /** Create User */
    post: operations["create_user_api_v1_users_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/users/{user_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get User */
    get: operations["get_user_api_v1_users__user_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update User */
    patch: operations["update_user_api_v1_users__user_id__patch"];
    trace?: never;
  };
  "/api/v1/customers": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Customers */
    get: operations["get_customers_api_v1_customers_get"];
    put?: never;
    /** Post Customer */
    post: operations["post_customer_api_v1_customers_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/customers/follow-ups": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Follow Ups */
    get: operations["get_follow_ups_api_v1_customers_follow_ups_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/customers/{customer_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Customer By Id */
    get: operations["get_customer_by_id_api_v1_customers__customer_id__get"];
    put?: never;
    post?: never;
    /** Delete Customer */
    delete: operations["delete_customer_api_v1_customers__customer_id__delete"];
    options?: never;
    head?: never;
    /** Patch Customer */
    patch: operations["patch_customer_api_v1_customers__customer_id__patch"];
    trace?: never;
  };
  "/api/v1/customers/{customer_id}/interactions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Customer Interactions */
    get: operations["get_customer_interactions_api_v1_customers__customer_id__interactions_get"];
    put?: never;
    /** Post Customer Interaction */
    post: operations["post_customer_interaction_api_v1_customers__customer_id__interactions_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/email-drafts/generate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Generate Email Draft */
    post: operations["generate_email_draft_api_v1_email_drafts_generate_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/email-drafts": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Email Drafts */
    get: operations["get_email_drafts_api_v1_email_drafts_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/email-drafts/{email_draft_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Email Draft */
    get: operations["get_email_draft_api_v1_email_drafts__email_draft_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Patch Email Draft */
    patch: operations["patch_email_draft_api_v1_email_drafts__email_draft_id__patch"];
    trace?: never;
  };
  "/api/v1/email-drafts/{email_draft_id}/review": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Review Email Draft */
    post: operations["review_email_draft_api_v1_email_drafts__email_draft_id__review_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/email-drafts/{email_draft_id}/approve": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Approve Email Draft */
    post: operations["approve_email_draft_api_v1_email_drafts__email_draft_id__approve_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/email-drafts/{email_draft_id}/reject": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Reject Email Draft */
    post: operations["reject_email_draft_api_v1_email_drafts__email_draft_id__reject_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/imports/customers/preview": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Preview Customer Import */
    post: operations["preview_customer_import_api_v1_imports_customers_preview_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/imports/{import_job_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Import */
    get: operations["get_import_api_v1_imports__import_job_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/imports/{import_job_id}/errors": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Import Errors */
    get: operations["get_import_errors_api_v1_imports__import_job_id__errors_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/imports/{import_job_id}/commit": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Commit Customer Import */
    post: operations["commit_customer_import_api_v1_imports__import_job_id__commit_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/imports/{import_job_id}/errors/download": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Download Import Errors */
    get: operations["download_import_errors_api_v1_imports__import_job_id__errors_download_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/power-bi/reports": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Power Bi Reports */
    get: operations["get_power_bi_reports_api_v1_power_bi_reports_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/power-bi/embed-config": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Post Power Bi Embed Config */
    post: operations["post_power_bi_embed_config_api_v1_power_bi_embed_config_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/power-bi/refresh-status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Power Bi Refresh Status */
    get: operations["get_power_bi_refresh_status_api_v1_power_bi_refresh_status_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/support-tickets": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Support Tickets */
    get: operations["get_support_tickets_api_v1_support_tickets_get"];
    put?: never;
    /** Post Support Ticket */
    post: operations["post_support_ticket_api_v1_support_tickets_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/support-tickets/{ticket_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Support Ticket */
    get: operations["get_support_ticket_api_v1_support_tickets__ticket_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Patch Support Ticket */
    patch: operations["patch_support_ticket_api_v1_support_tickets__ticket_id__patch"];
    trace?: never;
  };
  "/api/v1/support-tickets/{ticket_id}/comments": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Post Ticket Comment */
    post: operations["post_ticket_comment_api_v1_support_tickets__ticket_id__comments_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/audit-logs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Audit Logs */
    get: operations["get_audit_logs_api_v1_audit_logs_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** AuditLogPageResponse */
    AuditLogPageResponse: {
      /** Items */
      items: components["schemas"]["AuditLogResponse"][];
      meta: components["schemas"]["PageMeta"];
    };
    /** AuditLogResponse */
    AuditLogResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Actorid */
      actorId: string | null;
      /** Action */
      action: string;
      /** Entitytype */
      entityType: string;
      /** Entityid */
      entityId: string | null;
      /** Metadatajson */
      metadataJson: {
        [key: string]: unknown;
      };
      /**
       * Createdat
       * Format: date-time
       */
      createdAt: string;
    };
    /** Body_preview_customer_import_api_v1_imports_customers_preview_post */
    Body_preview_customer_import_api_v1_imports_customers_preview_post: {
      /** File */
      file: string;
    };
    /** CustomerCreateRequest */
    CustomerCreateRequest: {
      /** Companyname */
      companyName: string;
      /** Contactname */
      contactName: string;
      /** Email */
      email?: string | null;
      /** Phone */
      phone?: string | null;
      /** Ownerid */
      ownerId?: string | null;
    };
    /** CustomerResponse */
    CustomerResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Companyname */
      companyName: string;
      /** Contactname */
      contactName: string;
      /** Email */
      email: string | null;
      /** Phone */
      phone: string | null;
      status: components["schemas"]["CustomerStatus"];
      /**
       * Ownerid
       * Format: uuid
       */
      ownerId: string;
      /**
       * Createdat
       * Format: date-time
       */
      createdAt: string;
      /**
       * Updatedat
       * Format: date-time
       */
      updatedAt: string;
    };
    /**
     * CustomerStatus
     * @enum {string}
     */
    CustomerStatus: "active" | "archived";
    /** CustomerUpdateRequest */
    CustomerUpdateRequest: {
      /** Companyname */
      companyName?: string | null;
      /** Contactname */
      contactName?: string | null;
      /** Email */
      email?: string | null;
      /** Phone */
      phone?: string | null;
      /** Ownerid */
      ownerId?: string | null;
      status?: components["schemas"]["CustomerStatus"] | null;
    };
    /** EmailDraftGenerateRequest */
    EmailDraftGenerateRequest: {
      /**
       * Customerid
       * Format: uuid
       */
      customerId: string;
      purpose: components["schemas"]["EmailPurpose"];
      language: components["schemas"]["EmailLanguage"];
      tone: components["schemas"]["EmailTone"];
    };
    /** EmailDraftRejectRequest */
    EmailDraftRejectRequest: {
      /** Reason */
      reason?: string | null;
    };
    /** EmailDraftResponse */
    EmailDraftResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Customerid
       * Format: uuid
       */
      customerId: string;
      /**
       * Createdbyid
       * Format: uuid
       */
      createdById: string;
      purpose: components["schemas"]["EmailPurpose"];
      language: components["schemas"]["EmailLanguage"];
      tone: components["schemas"]["EmailTone"];
      /** Subject */
      subject: string;
      /** Body */
      body: string;
      status: components["schemas"]["EmailDraftStatus"];
      /** Provider */
      provider: string;
      /** Model */
      model: string;
      /** Promptversion */
      promptVersion: string;
      /**
       * Createdat
       * Format: date-time
       */
      createdAt: string;
      /**
       * Updatedat
       * Format: date-time
       */
      updatedAt: string;
    };
    /** EmailDraftReviewRequest */
    EmailDraftReviewRequest: {
      /** Subject */
      subject?: string | null;
      /** Body */
      body?: string | null;
    };
    /**
     * EmailDraftStatus
     * @enum {string}
     */
    EmailDraftStatus: "draft" | "reviewed" | "approved" | "rejected";
    /** EmailDraftUpdateRequest */
    EmailDraftUpdateRequest: {
      /** Subject */
      subject?: string | null;
      /** Body */
      body?: string | null;
    };
    /**
     * EmailLanguage
     * @enum {string}
     */
    EmailLanguage: "vi" | "en";
    /**
     * EmailPurpose
     * @enum {string}
     */
    EmailPurpose: "followUp" | "introduction" | "reengagement";
    /**
     * EmailTone
     * @enum {string}
     */
    EmailTone: "professional" | "friendly" | "concise";
    /** FollowUpResponse */
    FollowUpResponse: {
      customer: components["schemas"]["CustomerResponse"];
      /** Lastinteractionat */
      lastInteractionAt: string | null;
      /** Duesince */
      dueSince: string | null;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** HealthResponse */
    HealthResponse: {
      /** Status */
      status: string;
      /** Service */
      service: string;
      /** Version */
      version: string;
    };
    /** ImportCommitResponse */
    ImportCommitResponse: {
      job: components["schemas"]["ImportJobResponse"];
      /** Createdcustomercount */
      createdCustomerCount: number;
      /** Createdinteractioncount */
      createdInteractionCount: number;
    };
    /** ImportErrorResponse */
    ImportErrorResponse: {
      /** Rownumber */
      rowNumber: number;
      /** Fieldname */
      fieldName: string;
      /** Message */
      message: string;
    };
    /** ImportJobResponse */
    ImportJobResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Filename */
      fileName: string;
      status: components["schemas"]["ImportJobStatus"];
      /** Totalrows */
      totalRows: number;
      /** Validrows */
      validRows: number;
      /** Invalidrows */
      invalidRows: number;
      /**
       * Createdat
       * Format: date-time
       */
      createdAt: string;
      /** Completedat */
      completedAt: string | null;
    };
    /**
     * ImportJobStatus
     * @enum {string}
     */
    ImportJobStatus: "preview" | "ready" | "committed" | "failed";
    /** ImportPreviewResponse */
    ImportPreviewResponse: {
      job: components["schemas"]["ImportJobResponse"];
      /** Errors */
      errors: components["schemas"]["ImportErrorResponse"][];
    };
    /** InteractionCreateRequest */
    InteractionCreateRequest: {
      type: components["schemas"]["InteractionType"];
      /** Summary */
      summary: string;
      /**
       * Occurredat
       * Format: date-time
       */
      occurredAt: string;
    };
    /** InteractionResponse */
    InteractionResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Customerid
       * Format: uuid
       */
      customerId: string;
      /**
       * Userid
       * Format: uuid
       */
      userId: string;
      type: components["schemas"]["InteractionType"];
      /** Summary */
      summary: string;
      /**
       * Occurredat
       * Format: date-time
       */
      occurredAt: string;
      /**
       * Createdat
       * Format: date-time
       */
      createdAt: string;
    };
    /** InteractionTrendPoint */
    InteractionTrendPoint: {
      /**
       * Date
       * Format: date
       */
      date: string;
      /** Count */
      count: number;
    };
    /**
     * InteractionType
     * @enum {string}
     */
    InteractionType: "call" | "meeting" | "email" | "quote" | "note";
    /** InteractionsTrendResponse */
    InteractionsTrendResponse: {
      /** Points */
      points: components["schemas"]["InteractionTrendPoint"][];
    };
    /** LoginRequest */
    LoginRequest: {
      /** Email */
      email: string;
      /** Password */
      password: string;
    };
    /** LogoutRequest */
    LogoutRequest: {
      /** Refreshtoken */
      refreshToken: string;
    };
    /** OverviewResponse */
    OverviewResponse: {
      /** Totalcustomers */
      totalCustomers: number;
      /** Newcustomers */
      newCustomers: number;
      /** Activecustomers */
      activeCustomers: number;
      /** Interactions */
      interactions: number;
      /** Followupsdue */
      followUpsDue: number;
      /** Followuprate */
      followUpRate: number | null;
    };
    /** PageMeta */
    PageMeta: {
      /** Page */
      page: number;
      /** Pagesize */
      pageSize: number;
      /** Total */
      total: number;
      /** Pagecount */
      pageCount: number;
    };
    /** PageResponse[CustomerResponse] */
    PageResponse_CustomerResponse_: {
      /** Items */
      items: components["schemas"]["CustomerResponse"][];
      meta: components["schemas"]["PageMeta"];
    };
    /** PageResponse[UserResponse] */
    PageResponse_UserResponse_: {
      /** Items */
      items: components["schemas"]["UserResponse"][];
      meta: components["schemas"]["PageMeta"];
    };
    /** PowerBIEmbedConfigResponse */
    PowerBIEmbedConfigResponse: {
      /** Reportid */
      reportId: string;
      /** Embedurl */
      embedUrl: string;
      /** Accesstoken */
      accessToken: string;
      /**
       * Expiresat
       * Format: date-time
       */
      expiresAt: string;
      /**
       * Tokentype
       * @default EmbedToken
       */
      tokenType: string;
    };
    /** PowerBIRefreshStatusResponse */
    PowerBIRefreshStatusResponse: {
      /** Status */
      status: string;
      /** Lastrefreshedat */
      lastRefreshedAt: string | null;
      /** Nextrefreshat */
      nextRefreshAt: string | null;
      /** Message */
      message: string;
    };
    /** PowerBIReportResponse */
    PowerBIReportResponse: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      /** Description */
      description: string;
      /** Embedurl */
      embedUrl: string;
      /** Isavailable */
      isAvailable: boolean;
    };
    /** ProductCustomerCount */
    ProductCustomerCount: {
      /**
       * Productid
       * Format: uuid
       */
      productId: string;
      /** Productsku */
      productSku: string;
      /** Productname */
      productName: string;
      /** Customercount */
      customerCount: number;
    };
    /** RefreshRequest */
    RefreshRequest: {
      /** Refreshtoken */
      refreshToken: string;
    };
    /** SupportTicketCreateRequest */
    SupportTicketCreateRequest: {
      /** Title */
      title: string;
      /** Description */
      description: string;
      category: components["schemas"]["TicketCategory"];
      /** @default medium */
      priority: components["schemas"]["TicketPriority"];
    };
    /** SupportTicketDetailResponse */
    SupportTicketDetailResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Createdbyid
       * Format: uuid
       */
      createdById: string;
      /** Assigneeid */
      assigneeId: string | null;
      /** Title */
      title: string;
      /** Description */
      description: string;
      category: components["schemas"]["TicketCategory"];
      priority: components["schemas"]["TicketPriority"];
      status: components["schemas"]["TicketStatus"];
      /**
       * Createdat
       * Format: date-time
       */
      createdAt: string;
      /**
       * Updatedat
       * Format: date-time
       */
      updatedAt: string;
      /** Comments */
      comments: components["schemas"]["TicketCommentResponse"][];
    };
    /** SupportTicketResponse */
    SupportTicketResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Createdbyid
       * Format: uuid
       */
      createdById: string;
      /** Assigneeid */
      assigneeId: string | null;
      /** Title */
      title: string;
      /** Description */
      description: string;
      category: components["schemas"]["TicketCategory"];
      priority: components["schemas"]["TicketPriority"];
      status: components["schemas"]["TicketStatus"];
      /**
       * Createdat
       * Format: date-time
       */
      createdAt: string;
      /**
       * Updatedat
       * Format: date-time
       */
      updatedAt: string;
    };
    /** SupportTicketUpdateRequest */
    SupportTicketUpdateRequest: {
      status?: components["schemas"]["TicketStatus"] | null;
      priority?: components["schemas"]["TicketPriority"] | null;
      /** Assigneeid */
      assigneeId?: string | null;
    };
    /**
     * TicketCategory
     * @enum {string}
     */
    TicketCategory: "hardware" | "software" | "access" | "other";
    /** TicketCommentCreateRequest */
    TicketCommentCreateRequest: {
      /** Body */
      body: string;
    };
    /** TicketCommentResponse */
    TicketCommentResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Ticketid
       * Format: uuid
       */
      ticketId: string;
      /**
       * Authorid
       * Format: uuid
       */
      authorId: string;
      /** Body */
      body: string;
      /**
       * Createdat
       * Format: date-time
       */
      createdAt: string;
    };
    /**
     * TicketPriority
     * @enum {string}
     */
    TicketPriority: "low" | "medium" | "high" | "urgent";
    /**
     * TicketStatus
     * @enum {string}
     */
    TicketStatus: "open" | "in_progress" | "waiting" | "resolved" | "closed";
    /** TokenPairResponse */
    TokenPairResponse: {
      /** Accesstoken */
      accessToken: string;
      /** Refreshtoken */
      refreshToken: string;
      /**
       * Tokentype
       * @default bearer
       */
      tokenType: string;
      /** Expiresin */
      expiresIn: number;
    };
    /** UserCreateRequest */
    UserCreateRequest: {
      /** Email */
      email: string;
      /** Fullname */
      fullName: string;
      /** Password */
      password: string;
      /** @default staff */
      role: components["schemas"]["UserRole"];
    };
    /** UserResponse */
    UserResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Email */
      email: string;
      /** Fullname */
      fullName: string;
      role: components["schemas"]["UserRole"];
      /** Isactive */
      isActive: boolean;
      /**
       * Createdat
       * Format: date-time
       */
      createdAt: string;
      /**
       * Updatedat
       * Format: date-time
       */
      updatedAt: string;
    };
    /**
     * UserRole
     * @enum {string}
     */
    UserRole: "admin" | "staff";
    /** UserUpdateRequest */
    UserUpdateRequest: {
      /** Fullname */
      fullName?: string | null;
      role?: components["schemas"]["UserRole"] | null;
      /** Isactive */
      isActive?: boolean | null;
      /** Password */
      password?: string | null;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  get_health_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
    };
  };
  login_api_v1_auth_login_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TokenPairResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  refresh_api_v1_auth_refresh_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RefreshRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TokenPairResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  logout_api_v1_auth_logout_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LogoutRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  me_api_v1_auth_me_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserResponse"];
        };
      };
    };
  };
  get_overview_api_v1_analytics_overview_get: {
    parameters: {
      query?: {
        start?: string | null;
        end?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OverviewResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_customers_by_product_api_v1_analytics_customers_by_product_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProductCustomerCount"][];
        };
      };
    };
  };
  get_interactions_trend_api_v1_analytics_interactions_trend_get: {
    parameters: {
      query?: {
        start?: string | null;
        end?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["InteractionsTrendResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_analytics_follow_ups_api_v1_analytics_follow_ups_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FollowUpResponse"][];
        };
      };
    };
  };
  list_users_api_v1_users_get: {
    parameters: {
      query?: {
        page?: number;
        page_size?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PageResponse_UserResponse_"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_user_api_v1_users_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserCreateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_user_api_v1_users__user_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_user_api_v1_users__user_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserUpdateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_customers_api_v1_customers_get: {
    parameters: {
      query?: {
        page?: number;
        page_size?: number;
        search?: string | null;
        status?: components["schemas"]["CustomerStatus"] | null;
        owner_id?: string | null;
        sortBy?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PageResponse_CustomerResponse_"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  post_customer_api_v1_customers_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CustomerCreateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CustomerResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_follow_ups_api_v1_customers_follow_ups_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FollowUpResponse"][];
        };
      };
    };
  };
  get_customer_by_id_api_v1_customers__customer_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        customer_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CustomerResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_customer_api_v1_customers__customer_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        customer_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  patch_customer_api_v1_customers__customer_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        customer_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CustomerUpdateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CustomerResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_customer_interactions_api_v1_customers__customer_id__interactions_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        customer_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["InteractionResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  post_customer_interaction_api_v1_customers__customer_id__interactions_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        customer_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["InteractionCreateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["InteractionResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  generate_email_draft_api_v1_email_drafts_generate_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["EmailDraftGenerateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EmailDraftResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_email_drafts_api_v1_email_drafts_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EmailDraftResponse"][];
        };
      };
    };
  };
  get_email_draft_api_v1_email_drafts__email_draft_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        email_draft_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EmailDraftResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  patch_email_draft_api_v1_email_drafts__email_draft_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        email_draft_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["EmailDraftUpdateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EmailDraftResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  review_email_draft_api_v1_email_drafts__email_draft_id__review_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        email_draft_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["EmailDraftReviewRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EmailDraftResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  approve_email_draft_api_v1_email_drafts__email_draft_id__approve_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        email_draft_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EmailDraftResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  reject_email_draft_api_v1_email_drafts__email_draft_id__reject_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        email_draft_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["EmailDraftRejectRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EmailDraftResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  preview_customer_import_api_v1_imports_customers_preview_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_preview_customer_import_api_v1_imports_customers_preview_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ImportPreviewResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_import_api_v1_imports__import_job_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        import_job_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ImportJobResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_import_errors_api_v1_imports__import_job_id__errors_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        import_job_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ImportErrorResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  commit_customer_import_api_v1_imports__import_job_id__commit_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        import_job_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ImportCommitResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  download_import_errors_api_v1_imports__import_job_id__errors_download_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        import_job_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_power_bi_reports_api_v1_power_bi_reports_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PowerBIReportResponse"][];
        };
      };
    };
  };
  post_power_bi_embed_config_api_v1_power_bi_embed_config_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PowerBIEmbedConfigResponse"];
        };
      };
    };
  };
  get_power_bi_refresh_status_api_v1_power_bi_refresh_status_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PowerBIRefreshStatusResponse"];
        };
      };
    };
  };
  get_support_tickets_api_v1_support_tickets_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SupportTicketResponse"][];
        };
      };
    };
  };
  post_support_ticket_api_v1_support_tickets_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SupportTicketCreateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SupportTicketResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_support_ticket_api_v1_support_tickets__ticket_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        ticket_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SupportTicketDetailResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  patch_support_ticket_api_v1_support_tickets__ticket_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        ticket_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SupportTicketUpdateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SupportTicketResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  post_ticket_comment_api_v1_support_tickets__ticket_id__comments_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        ticket_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TicketCommentCreateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TicketCommentResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_audit_logs_api_v1_audit_logs_get: {
    parameters: {
      query?: {
        page?: number;
        page_size?: number;
        action?: string | null;
        entityType?: string | null;
        entityId?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuditLogPageResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
